-- ============================================================================
-- The Fleshborn Chorus
-- English localization
-- ============================================================================

INSERT INTO Language_en_US (Tag, Text) VALUES
('TXT_KEY_TRAIT_FLESHBORN_ALL_IS_SUSTENANCE', 'All Is Sustenance'),
('TXT_KEY_TRAIT_FLESHBORN_ALL_IS_SUSTENANCE_SHORT', 'All Is Sustenance'),
('TXT_KEY_TRAIT_FLESHBORN_ALL_IS_SUSTENANCE_HELP', 'Cannot use [ICON_PRODUCTION] Production, construct World Wonders, purchase orders or tiles, or upgrade units with Gold. Select Grow Population or divert net [ICON_FOOD] Food into units at 115% cost, Colony Buds at 130%, buildings and normal projects at 135%, and active World Congress projects at 1:1. Cities cost 5 [ICON_FOOD] plus 0.75 per Citizen each turn, rounded up per city; Specialists cost 1 more. The capital has a +4 [ICON_FOOD] Founding Core and begins with a Harvester. Military units consume era-scaled [ICON_FOOD] and suffer The Hunger when underfed. [ICON_GOLD] Gold and [ICON_PEACE] Faith are digested into Food at 4:1 and 3:1. Ignores Happiness, maintenance, and strategic-resource requirements.'),

('TXT_KEY_LEADER_FLESHBORN_FIRST_MAW', 'The First Maw'),
('TXT_KEY_LEADER_FLESHBORN_FIRST_MAW_PEDIA', 'Before there were cities, there was appetite. Before there was speech, a mouth learned that other mouths could answer. The First Maw is not monarch, prophet, or parent. It is the earliest organ around which the Fleshborn Chorus learned to coordinate: a hunger old enough to remember being alone.[NEWLINE][NEWLINE]Under the First Maw, no wall is merely stone and no field is merely land. Every settlement is a stomach, every road a vein, and every army a mobile demand for calories. The Chorus does not accumulate wealth. It grows.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_FLESHBORN_FIRST_MAW', 'The First Maw'),

('TXT_KEY_CIV_FLESHBORN_DESC', 'The Fleshborn Chorus'),
('TXT_KEY_CIV_FLESHBORN_SHORT_DESC', 'Fleshborn Chorus'),
('TXT_KEY_CIV_FLESHBORN_ADJECTIVE', 'Fleshborn'),
('TXT_KEY_CIV_FLESHBORN_STRATEGY', 'Food is your population, infrastructure, expansion, and army. Put every city on Grow Population when it needs Citizens; select a unit or building when you are ready to freeze growth and spend net Food on that order. Feeding Fields, edible resources, and internal Food routes are the heart of the empire. Watch military Feeding Requirement in the Metabolism panel: an army larger than your surplus acquires The Hunger. Pillaged farms are an existential threat. World Wonders, mines, strategic resources, Gold, Faith, and Happiness are distractions.'),
('TXT_KEY_CIV_FLESHBORN_PEDIA', 'The Fleshborn Chorus is a distributed biological civilization whose settlements are organs and whose armies are grown bodies. Its economy collapses the normal categories of empire into one question: is there enough to eat?[NEWLINE][NEWLINE]Production is inert. When a city selects a unit or building, the city freezes population growth and diverts its usable Food into that order. Buildings are deliberately more expensive than units because agricultural infrastructure compounds every part of the economy. The explicit Grow Population process returns all usable Food to growth.[NEWLINE][NEWLINE]Width and military scale are constrained by Metabolic Burden. Every city and Citizen consumes extra Food, Specialists consume still more, and military organisms draw an empire-wide era-scaled feeding cost. If the army asks for more Food than the empire can produce, The Hunger reduces combat strength and healing, eventually stopping new military growth.[NEWLINE][NEWLINE]Gold and Faith are not alternate economies. They are digested inefficiently into Food. Happiness and strategic resources are ignored. Biological copies replace every stock unit or building that would consume Horses, Iron, Coal, Oil, Aluminum, or Uranium. The Chorus cannot construct World Wonders. Its monument is itself.'),
('TXT_KEY_CIV5_FLESHBORN', 'The Fleshborn Chorus'),
('TXT_KEY_CIV5_FLESHBORN_HEADING_1', 'One Organ, Many Mouths'),
('TXT_KEY_CIV5_FLESHBORN_TEXT_1', 'No single body contains the Chorus. A Brood Node may be burned, a warform may be severed, and a neural cavity may fall silent, yet the organism persists wherever appetite can still answer appetite. What outsiders call cities are organs temporarily rooted in fertile ground.'),
('TXT_KEY_CIV5_FLESHBORN_HEADING_2', 'All Is Sustenance'),
('TXT_KEY_CIV5_FLESHBORN_TEXT_2', 'Metal is not wealth to the Chorus. Gold is a soft, indigestible mineral. Iron is a hard, indigestible mineral. Oil is foul liquid trapped beneath edible soil. Only living mass can become more living mass, so the Chorus measures possibility in calories.'),
('TXT_KEY_CIV5_FLESHBORN_HEADING_3', 'The First Maw'),
('TXT_KEY_CIV5_FLESHBORN_TEXT_3', 'The First Maw is the oldest remembered hunger: an ancestral organ whose impulse became the rhythm of the whole. It does not command with laws. It asks whether the Chorus has eaten, and every vein, claw, wing, and womb supplies the answer.'),
('TXT_KEY_CIV5_DOM_FLESHBORN_TEXT', 'First Maw, oldest hunger of the Fleshborn Chorus: the world before you mistakes glitter for value and stone for strength. Let other peoples count coins and quarrel over metal. You require calories. Root your Brood Nodes beside warm rivers, spread the Feeding Fields, and grow every answer your enemies demand. Will the Chorus starve in silence, or will all the world become sustenance?'),

('TXT_KEY_PROCESS_FLESHBORN_GROWTH', 'Grow Population'),
('TXT_KEY_PROCESS_FLESHBORN_GROWTH_HELP', 'Do not grow a project. All usable [ICON_FOOD] Food remains available for population growth.'),
('TXT_KEY_PROCESS_FLESHBORN_GROWTH_STRATEGY', 'Choose Grow Population whenever this Brood Node should add Citizens instead of growing a unit or building.'),

('TXT_KEY_UNIT_FLESHBORN_DEVOURER', 'Devourer Form'),
('TXT_KEY_UNIT_FLESHBORN_DEVOURER_HELP', 'Swordsman replacement. Requires no Iron and no maintenance. When an adjacent Devourer helps kill a military unit, 25% of the victim''s Combat Strength is added as [ICON_FOOD] Food to the nearest Brood Node.'),
('TXT_KEY_UNIT_FLESHBORN_DEVOURER_STRATEGY', 'A resource-free Swordsman that can partially feed the Chorus during close combat.'),
('TXT_KEY_UNIT_FLESHBORN_DEVOURER_PEDIA', 'The Devourer is a compact knot of jaws, grasping tendons, and digestive bladders. It is sent where the Chorus expects fresh resistance. What survives the first impact becomes fuel for the next.'),

('TXT_KEY_UNIT_FLESHBORN_HARVESTER', 'Harvester'),
('TXT_KEY_UNIT_FLESHBORN_HARVESTER_HELP', 'Worker replacement. Builds Feeding Fields, Roads, and normal non-Farm improvements. Feeding Fields metabolize Wheat, Bananas, Cattle, Sheep, Deer, Sugar, and Citrus. May digest Forest for 20 [ICON_FOOD], Jungle for 15, or Marsh for 12, feeding the nearest Brood Node instead of producing [ICON_PRODUCTION] Production.'),
('TXT_KEY_UNIT_FLESHBORN_HARVESTER_STRATEGY', 'Use Harvesters to spread Feeding Fields, consume edible resources, and convert unwanted features directly into Food.'),
('TXT_KEY_UNIT_FLESHBORN_HARVESTER_PEDIA', 'A Harvester is equal parts limb, mouth, and patient tool. Its task is not to cultivate land in the human sense, but to connect useful biomass to the nearest hungry organ.'),

('TXT_KEY_UNIT_FLESHBORN_COLONY_BUD', 'Colony Bud'),
('TXT_KEY_UNIT_FLESHBORN_COLONY_BUD_HELP', 'Settler replacement grown for 130% of the normal cost in [ICON_FOOD]. On completion, the parent city loses 1 Population. Founds a new Brood Node.'),
('TXT_KEY_UNIT_FLESHBORN_COLONY_BUD_STRATEGY', 'Expansion consumes Food twice: once to grow the Bud and once as living Population torn from its parent.'),
('TXT_KEY_UNIT_FLESHBORN_COLONY_BUD_PEDIA', 'A Colony Bud is a sealed packet of memory, digestive tissue, and reproductive mass. When it is ready, the parent organ tears away a living portion of itself and sends that portion crawling toward fertile ground.'),

('TXT_KEY_BUILDING_FLESHBORN_DIGESTIVE_CHAMBER', 'Digestive Chamber'),
('TXT_KEY_BUILDING_FLESHBORN_DIGESTIVE_CHAMBER_HELP', 'Granary replacement. No maintenance. Retains the Granary''s Food effects, keeps an additional 15% [ICON_FOOD] Food after growth, and reduces the Food cost of biological orders in this city by 5%.'),
('TXT_KEY_BUILDING_FLESHBORN_DIGESTIVE_CHAMBER_STRATEGY', 'The essential stomach-and-womb of a Brood Node. It improves both population recovery and project efficiency.'),
('TXT_KEY_BUILDING_FLESHBORN_DIGESTIVE_CHAMBER_PEDIA', 'The Digestive Chamber is not clearly a warehouse, stomach, or womb. It receives biomass, remembers its useful shapes, and releases either a larger city or a completed organism.'),

('TXT_KEY_BUILDING_FLESHBORN_NEURAL_CLUSTER', 'Neural Cluster'),
('TXT_KEY_BUILDING_FLESHBORN_NEURAL_CLUSTER_HELP', 'Library replacement. No maintenance. Generates +1 [ICON_RESEARCH] Science for every 3 [ICON_FOOD] Food consumed by this city''s population, including additional Specialist metabolism. The fixed city-organ burden does not count.'),
('TXT_KEY_BUILDING_FLESHBORN_NEURAL_CLUSTER_STRATEGY', 'Feed large Brood Nodes to turn living mass into thought. Population and Specialists increase both the Cluster''s Science and the city''s metabolic demand.'),
('TXT_KEY_BUILDING_FLESHBORN_NEURAL_CLUSTER_PEDIA', 'A Neural Cluster is an inward-folding web of ganglia through which appetite becomes memory and memory becomes prediction. It does not study books. It learns from every calorie spent sustaining the minds joined to it.'),

('TXT_KEY_BUILDING_FLESHBORN_BIO_FACTORY', 'Industrial Stomach'),
('TXT_KEY_BUILDING_FLESHBORN_BIO_FACTORY_HELP', 'Factory replacement. Retains the active Community Patch effects, requires no Coal, and has no Gold maintenance.'),
('TXT_KEY_BUILDING_FLESHBORN_BIO_HYDRO_PLANT', 'Current Organ'),
('TXT_KEY_BUILDING_FLESHBORN_BIO_HYDRO_PLANT_HELP', 'Hydro Plant replacement. Retains the active Community Patch effects, requires no Aluminum, and has no Gold maintenance.'),
('TXT_KEY_BUILDING_FLESHBORN_BIO_NUCLEAR_PLANT', 'Fission Cyst'),
('TXT_KEY_BUILDING_FLESHBORN_BIO_NUCLEAR_PLANT_HELP', 'Nuclear Plant replacement. Retains the active Community Patch effects, requires no Uranium, and has no Gold maintenance.'),
('TXT_KEY_BUILDING_FLESHBORN_BIO_SPACESHIP_FACTORY', 'Ascension Womb'),
('TXT_KEY_BUILDING_FLESHBORN_BIO_SPACESHIP_FACTORY_HELP', 'Spaceship Factory replacement. Retains the active Community Patch effects, requires no Aluminum, and has no Gold maintenance.'),

('TXT_KEY_BUILDING_FLESHBORN_METABOLISM', 'Metabolic State'),
('TXT_KEY_BUILDING_FLESHBORN_METABOLISM_HELP', 'Hidden state used to suppress Production and apply the Chorus economy.'),
('TXT_KEY_BUILDING_FLESHBORN_FOUNDING_CORE', 'Founding Core'),
('TXT_KEY_BUILDING_FLESHBORN_FOUNDING_CORE_HELP', 'The current capital receives +4 [ICON_FOOD] Food so the first organism can establish its Feeding Fields before the full metabolic burden takes hold.'),
('TXT_KEY_BUILDING_FLESHBORN_BLOOM', 'Blooming Cycle'),
('TXT_KEY_BUILDING_FLESHBORN_BLOOM_HELP', '+10% [ICON_FOOD] Food during a Golden Age.'),

('TXT_KEY_IMPROVEMENT_FLESHBORN_FEEDING_FIELD', 'Feeding Field'),
('TXT_KEY_IMPROVEMENT_FLESHBORN_FEEDING_FIELD_HELP', '+1 [ICON_FOOD] Food. +1 with Fresh Water, +1 at Civil Service, and +1 at Fertilizer. A worked Feeding Field with at least four adjacent Feeding Fields gains +1 Food (maximum +1). Metabolizes Wheat (+1), Bananas, Cattle, Sheep, or Deer (+2), and Sugar or Citrus (+3). Edible luxuries are not connected for trade. May preserve Marsh; Forest and Jungle must be digested first.'),
('TXT_KEY_IMPROVEMENT_FLESHBORN_FEEDING_FIELD_PEDIA', 'A Feeding Field is a thin agricultural organ spread across the soil. Rootlets sort edible matter, capillaries draw water, and the whole mat contracts toward the Brood Node when it is time to feed. It engulfs edible resources without erasing them from the land, converting their useful biomass into nourishment rather than commerce.'),
('TXT_KEY_BUILD_FLESHBORN_FEEDING_FIELD', 'Construct a Feeding Field'),
('TXT_KEY_BUILD_FLESHBORN_FEEDING_FIELD_HELP', 'Constructs a Feeding Field. May replace the normal improvement on Wheat, Bananas, Cattle, Sheep, Deer, Sugar, or Citrus and metabolize the worked resource into extra Food.'),
('TXT_KEY_BUILD_FLESHBORN_FEEDING_FIELD_REC', 'Build Feeding Fields in connected clusters and over edible resources. Digest Forest or Jungle before engulfing a covered resource.'),
('TXT_KEY_BUILD_FLESHBORN_DIGEST_FOREST', 'Digest Forest'),
('TXT_KEY_BUILD_FLESHBORN_DIGEST_JUNGLE', 'Digest Jungle'),
('TXT_KEY_BUILD_FLESHBORN_DIGEST_MARSH', 'Digest Marsh'),
('TXT_KEY_BUILD_FLESHBORN_DIGEST_HELP', 'Removes the feature and sends stored [ICON_FOOD] Food to the nearest Brood Node.'),

('TXT_KEY_PROMOTION_FLESHBORN_HUNGER', 'The Hunger'),
('TXT_KEY_PROMOTION_FLESHBORN_HUNGER_1_HELP', 'Army feeding is short by up to 10%: -3% Combat Strength and -2 healing.'),
('TXT_KEY_PROMOTION_FLESHBORN_HUNGER_2_HELP', 'Army feeding is short by up to 20%: -6% Combat Strength and -3 healing.'),
('TXT_KEY_PROMOTION_FLESHBORN_HUNGER_3_HELP', 'Army feeding is short by up to 30%: -9% Combat Strength and -5 healing.'),
('TXT_KEY_PROMOTION_FLESHBORN_HUNGER_4_HELP', 'Army feeding is short by up to 40%: -12% Combat Strength and -6 healing.'),
('TXT_KEY_PROMOTION_FLESHBORN_HUNGER_5_HELP', 'Army feeding is short by up to 50%: -15% Combat Strength and -8 healing.'),
('TXT_KEY_PROMOTION_FLESHBORN_HUNGER_6_HELP', 'Army feeding is short by up to 60%: -18% Combat Strength and -9 healing.'),
('TXT_KEY_PROMOTION_FLESHBORN_HUNGER_7_HELP', 'Army feeding is short by up to 70%: -21% Combat Strength, -11 healing, and new military growth is disabled.'),
('TXT_KEY_PROMOTION_FLESHBORN_HUNGER_8_HELP', 'Army feeding is short by up to 80%: -24% Combat Strength, -12 healing, and new military growth is disabled.'),
('TXT_KEY_PROMOTION_FLESHBORN_HUNGER_9_HELP', 'Army feeding is short by up to 90%: -27% Combat Strength, -14 healing, and new military growth is disabled.'),
('TXT_KEY_PROMOTION_FLESHBORN_HUNGER_10_HELP', 'Army feeding has completely failed: -30% Combat Strength, -15 healing, and new military growth is disabled.'),

('TXT_KEY_UNIT_FLESHBORN_HUNTER_FORM', 'Hunter Form'),
('TXT_KEY_UNIT_FLESHBORN_SPITTER_FORM', 'Spitter Form'),
('TXT_KEY_UNIT_FLESHBORN_SPINECASTER', 'Spinecaster'),
('TXT_KEY_UNIT_FLESHBORN_WARFORM', 'Warform'),
('TXT_KEY_UNIT_FLESHBORN_SPINE_RUNNER', 'Spine Runner'),
('TXT_KEY_UNIT_FLESHBORN_HUNTER_BEAST', 'Hunter Beast'),
('TXT_KEY_UNIT_FLESHBORN_RAVAGER', 'Ravager Form'),
('TXT_KEY_UNIT_FLESHBORN_RIPPER', 'Ripper Form'),
('TXT_KEY_UNIT_FLESHBORN_PIERCER', 'Piercer Form'),
('TXT_KEY_UNIT_FLESHBORN_GREATER_RAVAGER', 'Greater Ravager'),
('TXT_KEY_UNIT_FLESHBORN_YOUNG_BEHEMOTH', 'Young Behemoth'),
('TXT_KEY_UNIT_FLESHBORN_BEHEMOTH', 'Behemoth'),
('TXT_KEY_UNIT_FLESHBORN_APEX_BEHEMOTH', 'Apex Behemoth'),
('TXT_KEY_UNIT_FLESHBORN_SHELLBACK', 'Shellback'),
('TXT_KEY_UNIT_FLESHBORN_SPINE_SHIP', 'Spine Ship'),
('TXT_KEY_UNIT_FLESHBORN_LEVIATHAN', 'Leviathan'),
('TXT_KEY_UNIT_FLESHBORN_SKYHUNTER', 'Skyhunter'),
('TXT_KEY_UNIT_FLESHBORN_APEX_SKYHUNTER', 'Apex Skyhunter'),
('TXT_KEY_UNIT_FLESHBORN_BLIGHTWING', 'Blightwing'),
('TXT_KEY_UNIT_FLESHBORN_NIGHT_BLIGHTWING', 'Night Blightwing'),
('TXT_KEY_UNIT_FLESHBORN_HOVERMAW', 'Hovermaw'),
('TXT_KEY_UNIT_FLESHBORN_BILE_CATHEDRAL', 'Bile Cathedral'),
('TXT_KEY_UNIT_FLESHBORN_APEX_WARFORM', 'Apex Warform'),
('TXT_KEY_UNIT_FLESHBORN_PLAGUE_SEED', 'Plague Seed'),
('TXT_KEY_UNIT_FLESHBORN_EXTINCTION_CYST', 'Extinction Cyst'),
('TXT_KEY_UNIT_FLESHBORN_STAR_WOMB', 'Star Womb'),
('TXT_KEY_UNIT_FLESHBORN_VOID_HEART', 'Void Heart'),
('TXT_KEY_UNIT_FLESHBORN_STAR_BRAIN', 'Star Brain'),
('TXT_KEY_UNIT_FLESHBORN_ASCENT_SAC', 'Ascent Sac'),

('TXT_KEY_CITY_FLESHBORN_FIRST_STOMACH', 'First Stomach'),
('TXT_KEY_CITY_FLESHBORN_ANTERIOR_NODE', 'Anterior Node'),
('TXT_KEY_CITY_FLESHBORN_BROOD_BASIN', 'Brood Basin'),
('TXT_KEY_CITY_FLESHBORN_FEEDING_ORGAN', 'Feeding Organ'),
('TXT_KEY_CITY_FLESHBORN_DEEP_GUT', 'Deep Gut'),
('TXT_KEY_CITY_FLESHBORN_NEURAL_CAVITY', 'Neural Cavity'),
('TXT_KEY_CITY_FLESHBORN_WESTERN_MAW', 'Western Maw'),
('TXT_KEY_CITY_FLESHBORN_VENTRAL_COLONY', 'Ventral Colony'),
('TXT_KEY_CITY_FLESHBORN_SPAWN_CHAMBER', 'Spawn Chamber'),
('TXT_KEY_CITY_FLESHBORN_HUNGER_BEYOND', 'Hunger Beyond'),
('TXT_KEY_CITY_FLESHBORN_RED_FOLD', 'Red Fold'),
('TXT_KEY_CITY_FLESHBORN_THIRD_LIVER', 'Third Liver'),
('TXT_KEY_CITY_FLESHBORN_HOLLOW_TONGUE', 'Hollow Tongue'),
('TXT_KEY_CITY_FLESHBORN_BONE_GARDEN', 'Bone Garden'),
('TXT_KEY_CITY_FLESHBORN_WARM_VAULT', 'Warm Vault'),
('TXT_KEY_CITY_FLESHBORN_CRAWLING_ROOT', 'Crawling Root'),
('TXT_KEY_CITY_FLESHBORN_PALE_SINEW', 'Pale Sinew'),
('TXT_KEY_CITY_FLESHBORN_GREAT_THROAT', 'Great Throat'),
('TXT_KEY_CITY_FLESHBORN_MEMORY_SAC', 'Memory Sac'),
('TXT_KEY_CITY_FLESHBORN_LAST_APPETITE', 'Last Appetite'),

('TXT_KEY_SPY_FLESHBORN_TASTE', 'Taste'),
('TXT_KEY_SPY_FLESHBORN_SCENT', 'Scent'),
('TXT_KEY_SPY_FLESHBORN_WHISPER', 'Whisper'),
('TXT_KEY_SPY_FLESHBORN_TREMOR', 'Tremor'),
('TXT_KEY_SPY_FLESHBORN_ECHO', 'Echo');
